"use client";

import { useState } from "react";
import { Sparkles, Save, BookOpen, PenTool } from "lucide-react";
import { useForm } from "react-hook-form";
import { motion } from "framer-motion";

import { useGenerateContentMutation } from "@/redux/api/aiApi";
import { Card } from "@/components/UI/card";
import { Input } from "@/components/UI/input";
import { Button } from "@/components/UI/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/UI/tabs";
import { Textarea } from "@/components/UI/textarea";

export default function TeachingDashboardPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-white">
          My Knowledge Assets
        </h1>
        <p className="mt-2 text-zinc-600 dark:text-zinc-400">
          Manage your purchased skills and create new listings to earn Knowledge Tokens.
        </p>
      </div>

      <Tabs defaultValue="teaching" className="w-full">
        <TabsList className="mb-6 grid w-full max-w-md grid-cols-2 rounded-full border border-white/60 bg-white/70 p-1 shadow-sm backdrop-blur-xl dark:border-white/10 dark:bg-zinc-900/60">
          <TabsTrigger value="learning" className="rounded-full px-6 text-sm font-medium data-[state=active]:bg-blue-600 data-[state=active]:text-white dark:data-[state=active]:bg-cyan-500 dark:data-[state=active]:text-zinc-950">
            <BookOpen className="mr-2 size-4" />
            My Purchases
          </TabsTrigger>
          <TabsTrigger value="teaching" className="rounded-full px-6 text-sm font-medium data-[state=active]:bg-blue-600 data-[state=active]:text-white dark:data-[state=active]:bg-cyan-500 dark:data-[state=active]:text-zinc-950">
            <PenTool className="mr-2 size-4" />
            My Listings
          </TabsTrigger>
        </TabsList>
        
        <TabsContent value="learning" className="mt-0">
          <Card className="flex min-h-64 items-center justify-center rounded-[2rem] border-dashed border-white/60 bg-white/40 p-6 backdrop-blur-xl dark:border-white/10 dark:bg-zinc-900/40">
            <p className="text-zinc-500">Your purchased skills will appear here.</p>
          </Card>
        </TabsContent>
        
        <TabsContent value="teaching" className="mt-0 space-y-6">
          <Card className="rounded-[2rem] border-white/60 bg-white/70 p-6 shadow-xl backdrop-blur-xl dark:border-white/10 dark:bg-zinc-900/60">
            <h2 className="mb-4 text-xl font-bold text-zinc-900 dark:text-white">Create New Skill Listing</h2>
            <CreateSkillForm />
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function CreateSkillForm() {
  const [generateContent, { isLoading }] = useGenerateContentMutation();
  const { register, handleSubmit, setValue, watch } = useForm({
    defaultValues: {
      title: "",
      category: "",
      shortDescription: "",
      price: "",
      lockedContent: ""
    }
  });

  const [pulseText, setPulseText] = useState("Architecting syllabus...");
  const titleVal = watch("title");

  const handleMagicFill = async () => {
    if (!titleVal) return;
    
    // Start pulse text
    const texts = ["Analyzing topic...", "Generating syllabus...", "Structuring content...", "Finalizing draft..."];
    let i = 0;
    const interval = setInterval(() => {
      i = (i + 1) % texts.length;
      setPulseText(texts[i]);
    }, 1200);

    try {
      const result = await generateContent({ prompt: titleVal }).unwrap();
      setValue("shortDescription", result.content || "An advanced, comprehensive guide generated by AI.");
      setValue("lockedContent", "Module 1: Introduction\nModule 2: Advanced Concepts\n\n(AI Generated Draft)");
    } catch (err) {
      console.error(err);
      // Fallback for demo
      setTimeout(() => {
        setValue("shortDescription", "Master this topic with comprehensive strategies and real-world examples. Designed for quick learning.");
        setValue("lockedContent", "https://github.com/example/repo\nSecret password: knowledge_is_power");
      }, 1500);
    } finally {
      clearInterval(interval);
    }
  };

  return (
    <form className="space-y-6" onSubmit={handleSubmit((d) => console.log(d))}>
      <div className="space-y-4">
        <div>
          <label className="mb-1.5 block text-sm font-medium text-zinc-700 dark:text-zinc-300">Skill Title</label>
          <div className="flex gap-3">
            <Input 
              {...register("title")} 
              placeholder="e.g., Advanced Next.js Patterns" 
              className="flex-1 rounded-2xl bg-white/80 dark:bg-zinc-950/50"
            />
            <Button 
              type="button" 
              onClick={handleMagicFill}
              disabled={isLoading || !titleVal}
              className="rounded-full bg-linear-to-r from-blue-600 to-indigo-600 text-white shadow-lg shadow-blue-600/20 hover:from-blue-700 hover:to-indigo-700 dark:from-cyan-500 dark:to-blue-500 dark:text-zinc-950"
            >
              {isLoading ? (
                <span className="flex items-center gap-2">
                  <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1.5, ease: "linear" }}>
                    <Sparkles className="size-4" />
                  </motion.div>
                  {pulseText}
                </span>
              ) : (
                <>
                  <Sparkles className="mr-2 size-4" />
                  AI Course Architect
                </>
              )}
            </Button>
          </div>
          <p className="mt-1.5 text-xs text-zinc-500">Type a title and let AI generate the curriculum.</p>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <div>
            <label className="mb-1.5 block text-sm font-medium text-zinc-700 dark:text-zinc-300">Category</label>
            <Input {...register("category")} placeholder="e.g., Development" className="rounded-2xl bg-white/80 dark:bg-zinc-950/50" />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-medium text-zinc-700 dark:text-zinc-300">Price (KT)</label>
            <Input {...register("price")} type="number" placeholder="50" className="rounded-2xl bg-white/80 dark:bg-zinc-950/50" />
          </div>
        </div>

        <div>
          <label className="mb-1.5 block text-sm font-medium text-zinc-700 dark:text-zinc-300">Short Description</label>
          <Textarea 
            {...register("shortDescription")} 
            placeholder="A brief pitch for your skill..." 
            className="min-h-[80px] rounded-2xl bg-white/80 dark:bg-zinc-950/50"
          />
        </div>

        <div>
          <label className="mb-1.5 block flex items-center gap-2 text-sm font-medium text-zinc-700 dark:text-zinc-300">
            Locked Content 
            <span className="rounded bg-blue-100 px-1.5 py-0.5 text-[10px] font-bold text-blue-700 dark:bg-cyan-900 dark:text-cyan-300">PRIVATE</span>
          </label>
          <Textarea 
            {...register("lockedContent")} 
            placeholder="Links to repos, videos, or raw knowledge that unlocks upon purchase." 
            className="min-h-[120px] rounded-2xl bg-zinc-50 font-mono text-sm dark:bg-zinc-950"
          />
        </div>
      </div>

      <div className="flex justify-end pt-4">
        <Button type="submit" className="rounded-full bg-zinc-900 px-8 text-white hover:bg-zinc-800 dark:bg-white dark:text-zinc-950 dark:hover:bg-zinc-200">
          <Save className="mr-2 size-4" />
          Publish Skill
        </Button>
      </div>
    </form>
  );
}
